/* =============================================================================
   SERVICE MANAGEMENT DATABASE  -  v2 (2026 rebuild of my 2021 UNLV project)
   -----------------------------------------------------------------------------
   Author   : Jomel Capili
   Engine   : MySQL 8.0+
   Domain   : Independent auto repair shop (Las Vegas, NV) - customers,
              vehicles, appointments, work orders, technicians, parts
              inventory, invoicing, payments and customer feedback.

   Run order
     01_schema.sql              <- this file (drops & recreates the database)
     02_seed_data.sql           generated by python/generate_data.py
     03_views.sql               reporting views used by the dashboard
     04_analysis_queries.sql    business questions (CTEs, window functions)
     05_data_quality_checks.sql integrity / sanity checks (all should return 0)
     06_maintenance_examples.sql corrected UPDATE / DELETE patterns

   Design notes
     * 3NF. Every non-key column depends on the key, the whole key, and
       nothing but the key. Totals (invoice amount, stock on hand) are
       DERIVED in views instead of stored, so they can never drift.
     * Prices are snapshotted on the transaction lines (work_order_part,
       work_order_service) because the price at the time of sale is a fact
       about that sale, not about the catalog.
     * Every relationship is enforced with a foreign key and every status /
       code column is enforced with a CHECK constraint (MySQL 8.0.16+).
     * Surrogate integer keys everywhere; natural keys (VIN, SKU, email)
       are kept UNIQUE.
   ============================================================================= */

DROP DATABASE IF EXISTS service_management;
CREATE DATABASE service_management
    CHARACTER SET utf8mb4
    COLLATE utf8mb4_0900_ai_ci;
USE service_management;

-- -----------------------------------------------------------------------------
-- 1. customer : one row per customer account (retail driver or fleet account)
-- -----------------------------------------------------------------------------
CREATE TABLE customer (
    customer_id          INT UNSIGNED   NOT NULL AUTO_INCREMENT,
    first_name           VARCHAR(50)    NOT NULL,
    last_name            VARCHAR(50)    NOT NULL,
    company_name         VARCHAR(80)        NULL,      -- fleet accounts only
    phone                VARCHAR(20)        NULL,
    email                VARCHAR(120)       NULL,
    zip_code             CHAR(5)        NOT NULL,
    acquisition_channel  VARCHAR(20)    NOT NULL,
    customer_since       DATE           NOT NULL,
    CONSTRAINT pk_customer         PRIMARY KEY (customer_id),
    CONSTRAINT uq_customer_email   UNIQUE (email),
    CONSTRAINT ck_customer_channel CHECK (acquisition_channel IN
        ('Walk-in','Google Search','Referral','Yelp','Social Media','Fleet Account')),
    CONSTRAINT ck_customer_zip     CHECK (REGEXP_LIKE(zip_code, '^[0-9]{5}$')),
    CONSTRAINT ck_customer_fleet   CHECK ((acquisition_channel = 'Fleet Account') = (company_name IS NOT NULL))
);

-- -----------------------------------------------------------------------------
-- 2. vehicle : a customer owns zero-to-many vehicles
-- -----------------------------------------------------------------------------
CREATE TABLE vehicle (
    vehicle_id   INT UNSIGNED       NOT NULL AUTO_INCREMENT,
    customer_id  INT UNSIGNED       NOT NULL,
    vin          CHAR(17)           NOT NULL,
    make         VARCHAR(30)        NOT NULL,
    model        VARCHAR(40)        NOT NULL,
    model_year   SMALLINT UNSIGNED  NOT NULL,
    CONSTRAINT pk_vehicle       PRIMARY KEY (vehicle_id),
    CONSTRAINT uq_vehicle_vin   UNIQUE (vin),
    CONSTRAINT fk_vehicle_customer FOREIGN KEY (customer_id) REFERENCES customer (customer_id),
    CONSTRAINT ck_vehicle_year  CHECK (model_year BETWEEN 1981 AND 2027),
    -- 17 chars, upper-case, and never the letters I, O or Q (ISO 3779)
    CONSTRAINT ck_vehicle_vin   CHECK (REGEXP_LIKE(vin, '^[A-HJ-NPR-Z0-9]{17}$', 'c'))
);

-- -----------------------------------------------------------------------------
-- 3. mechanic : shop employees (no longer tied to a customer - see fix log)
-- -----------------------------------------------------------------------------
CREATE TABLE mechanic (
    mechanic_id       SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
    first_name        VARCHAR(50)       NOT NULL,
    last_name         VARCHAR(50)       NOT NULL,
    phone             VARCHAR(20)       NOT NULL,
    skill_level       VARCHAR(20)       NOT NULL,
    hourly_wage       DECIMAL(6,2)      NOT NULL,
    hire_date         DATE              NOT NULL,
    termination_date  DATE                  NULL,
    CONSTRAINT pk_mechanic       PRIMARY KEY (mechanic_id),
    CONSTRAINT ck_mechanic_skill CHECK (skill_level IN ('Apprentice','Technician','Master Technician')),
    CONSTRAINT ck_mechanic_wage  CHECK (hourly_wage > 0),
    CONSTRAINT ck_mechanic_dates CHECK (termination_date IS NULL OR termination_date >= hire_date)
);

-- -----------------------------------------------------------------------------
-- 4. service_type : menu of labor operations with flat-rate "book" hours
-- -----------------------------------------------------------------------------
CREATE TABLE service_type (
    service_type_id   SMALLINT UNSIGNED NOT NULL,
    service_name      VARCHAR(60)       NOT NULL,
    service_category  VARCHAR(30)       NOT NULL,
    book_hours        DECIMAL(4,2)      NOT NULL,
    CONSTRAINT pk_service_type      PRIMARY KEY (service_type_id),
    CONSTRAINT uq_service_type_name UNIQUE (service_name),
    CONSTRAINT ck_service_type_hrs  CHECK (book_hours > 0)
);

-- -----------------------------------------------------------------------------
-- 5. supplier : parts vendors and their quoted lead time
-- -----------------------------------------------------------------------------
CREATE TABLE supplier (
    supplier_id       SMALLINT UNSIGNED NOT NULL,
    supplier_name     VARCHAR(80)       NOT NULL,
    phone             VARCHAR(20)       NOT NULL,
    quoted_lead_days  TINYINT UNSIGNED  NOT NULL,
    CONSTRAINT pk_supplier      PRIMARY KEY (supplier_id),
    CONSTRAINT uq_supplier_name UNIQUE (supplier_name)
);

-- -----------------------------------------------------------------------------
-- 6. part : parts catalog. Stock on hand is DERIVED (v_part_inventory),
--           never stored, so it cannot drift out of sync with transactions.
-- -----------------------------------------------------------------------------
CREATE TABLE part (
    part_id        SMALLINT UNSIGNED NOT NULL,
    sku            VARCHAR(20)       NOT NULL,
    part_name      VARCHAR(80)       NOT NULL,
    part_category  VARCHAR(30)       NOT NULL,
    supplier_id    SMALLINT UNSIGNED NOT NULL,
    unit_cost      DECIMAL(8,2)      NOT NULL,   -- current replacement cost
    unit_price     DECIMAL(8,2)      NOT NULL,   -- current retail price
    reorder_point  SMALLINT UNSIGNED NOT NULL,   -- reorder when on-hand + on-order <= this
    reorder_qty    SMALLINT UNSIGNED NOT NULL,   -- 0 = special-order only, never stocked
    CONSTRAINT pk_part          PRIMARY KEY (part_id),
    CONSTRAINT uq_part_sku      UNIQUE (sku),
    CONSTRAINT fk_part_supplier FOREIGN KEY (supplier_id) REFERENCES supplier (supplier_id),
    CONSTRAINT ck_part_cost     CHECK (unit_cost > 0),
    CONSTRAINT ck_part_markup   CHECK (unit_price >= unit_cost)
);

-- -----------------------------------------------------------------------------
-- 7. appointment : a booking for a specific vehicle at a specific time
-- -----------------------------------------------------------------------------
CREATE TABLE appointment (
    appointment_id   INT UNSIGNED NOT NULL AUTO_INCREMENT,
    vehicle_id       INT UNSIGNED NOT NULL,
    booked_at        DATETIME     NOT NULL,
    scheduled_start  DATETIME     NOT NULL,
    status           VARCHAR(10)  NOT NULL,
    CONSTRAINT pk_appointment         PRIMARY KEY (appointment_id),
    CONSTRAINT fk_appointment_vehicle FOREIGN KEY (vehicle_id) REFERENCES vehicle (vehicle_id),
    CONSTRAINT ck_appointment_status  CHECK (status IN ('Scheduled','Arrived','No-Show','Cancelled')),
    CONSTRAINT ck_appointment_order   CHECK (booked_at <= scheduled_start),
    INDEX ix_appointment_start (scheduled_start)
);

-- -----------------------------------------------------------------------------
-- 8. work_order : one visit / repair order. The assigned mechanic is the
--                 single responsible technician (business rule E).
--                 parent_work_order_id links a warranty "comeback" to the
--                 original job (self-referencing relationship).
-- -----------------------------------------------------------------------------
CREATE TABLE work_order (
    work_order_id         INT UNSIGNED      NOT NULL AUTO_INCREMENT,
    vehicle_id            INT UNSIGNED      NOT NULL,
    appointment_id        INT UNSIGNED          NULL,   -- NULL = walk-in
    mechanic_id           SMALLINT UNSIGNED NOT NULL,
    parent_work_order_id  INT UNSIGNED          NULL,   -- NOT NULL = warranty rework
    opened_at             DATETIME          NOT NULL,
    promised_at           DATETIME          NOT NULL,
    completed_at          DATETIME              NULL,
    status                VARCHAR(20)       NOT NULL,
    odometer_miles        INT UNSIGNED      NOT NULL,
    CONSTRAINT pk_work_order             PRIMARY KEY (work_order_id),
    CONSTRAINT uq_work_order_appointment UNIQUE (appointment_id),
    CONSTRAINT fk_work_order_vehicle     FOREIGN KEY (vehicle_id)           REFERENCES vehicle (vehicle_id),
    CONSTRAINT fk_work_order_appointment FOREIGN KEY (appointment_id)       REFERENCES appointment (appointment_id),
    CONSTRAINT fk_work_order_mechanic    FOREIGN KEY (mechanic_id)          REFERENCES mechanic (mechanic_id),
    CONSTRAINT fk_work_order_parent      FOREIGN KEY (parent_work_order_id) REFERENCES work_order (work_order_id),
    CONSTRAINT ck_work_order_status      CHECK (status IN ('Open','In Progress','Waiting on Parts','Completed')),
    CONSTRAINT ck_work_order_promise     CHECK (promised_at > opened_at),
    CONSTRAINT ck_work_order_complete    CHECK (completed_at IS NULL OR completed_at > opened_at),
    CONSTRAINT ck_work_order_status_date CHECK ((status = 'Completed') = (completed_at IS NOT NULL)),
    INDEX ix_work_order_opened (opened_at),
    INDEX ix_work_order_status (status)
);

-- -----------------------------------------------------------------------------
-- 9. work_order_service : labor lines (M:N work_order <-> service_type)
-- -----------------------------------------------------------------------------
CREATE TABLE work_order_service (
    work_order_id    INT UNSIGNED      NOT NULL,
    service_type_id  SMALLINT UNSIGNED NOT NULL,
    hours_billed     DECIMAL(5,2)      NOT NULL,   -- flat-rate hours charged (0 on warranty rework)
    hours_actual     DECIMAL(5,2)      NOT NULL,   -- clocked hours
    labor_rate       DECIMAL(6,2)      NOT NULL,   -- shop rate at time of service
    CONSTRAINT pk_work_order_service PRIMARY KEY (work_order_id, service_type_id),
    CONSTRAINT fk_wos_work_order     FOREIGN KEY (work_order_id)   REFERENCES work_order (work_order_id),
    CONSTRAINT fk_wos_service_type   FOREIGN KEY (service_type_id) REFERENCES service_type (service_type_id),
    CONSTRAINT ck_wos_hours          CHECK (hours_billed >= 0 AND hours_actual > 0),
    CONSTRAINT ck_wos_rate           CHECK (labor_rate > 0)
);

-- -----------------------------------------------------------------------------
-- 10. work_order_part : parts installed on a job (M:N work_order <-> part).
--     Replaces the 2021 mechanic_uses table, which could not say WHICH job
--     a part went into.
-- -----------------------------------------------------------------------------
CREATE TABLE work_order_part (
    work_order_id  INT UNSIGNED      NOT NULL,
    part_id        SMALLINT UNSIGNED NOT NULL,
    quantity       SMALLINT UNSIGNED NOT NULL,
    unit_cost      DECIMAL(8,2)      NOT NULL,   -- cost at time of use
    unit_price     DECIMAL(8,2)      NOT NULL,   -- price charged (0 on warranty rework)
    was_in_stock   BOOLEAN           NOT NULL,   -- FALSE = had to be special-ordered
    CONSTRAINT pk_work_order_part PRIMARY KEY (work_order_id, part_id),
    CONSTRAINT fk_wop_work_order  FOREIGN KEY (work_order_id) REFERENCES work_order (work_order_id),
    CONSTRAINT fk_wop_part        FOREIGN KEY (part_id)       REFERENCES part (part_id),
    CONSTRAINT ck_wop_quantity    CHECK (quantity > 0),
    CONSTRAINT ck_wop_amounts     CHECK (unit_cost > 0 AND unit_price >= 0)
);

-- -----------------------------------------------------------------------------
-- 11. part_order : every unit that enters inventory - opening balance,
--     automatic replenishment, or a special order for one specific job.
--     received_date IS NULL means the order is still in transit.
-- -----------------------------------------------------------------------------
CREATE TABLE part_order (
    part_order_id  INT UNSIGNED      NOT NULL AUTO_INCREMENT,
    part_id        SMALLINT UNSIGNED NOT NULL,
    work_order_id  INT UNSIGNED          NULL,
    order_type     VARCHAR(15)       NOT NULL,
    ordered_date   DATE              NOT NULL,
    expected_date  DATE              NOT NULL,
    received_date  DATE                  NULL,
    quantity       SMALLINT UNSIGNED NOT NULL,
    unit_cost      DECIMAL(8,2)      NOT NULL,
    CONSTRAINT pk_part_order          PRIMARY KEY (part_order_id),
    CONSTRAINT fk_part_order_part     FOREIGN KEY (part_id)       REFERENCES part (part_id),
    CONSTRAINT fk_part_order_wo       FOREIGN KEY (work_order_id) REFERENCES work_order (work_order_id),
    CONSTRAINT ck_part_order_type     CHECK (order_type IN ('Opening Balance','Replenishment','Special Order')),
    CONSTRAINT ck_part_order_special  CHECK ((order_type = 'Special Order') = (work_order_id IS NOT NULL)),
    CONSTRAINT ck_part_order_dates    CHECK (expected_date >= ordered_date
                                         AND (received_date IS NULL OR received_date >= ordered_date)),
    CONSTRAINT ck_part_order_qty      CHECK (quantity > 0 AND unit_cost > 0)
);

-- -----------------------------------------------------------------------------
-- 12. invoice : one per customer-pay work order. Amounts are derived from
--     the labor and parts lines in v_invoice_totals (3NF - no stored total).
--     Nevada taxes parts but not repair labor, so tax_rate applies to parts.
-- -----------------------------------------------------------------------------
CREATE TABLE invoice (
    invoice_id       INT UNSIGNED  NOT NULL AUTO_INCREMENT,
    work_order_id    INT UNSIGNED  NOT NULL,
    invoice_date     DATE          NOT NULL,
    discount_amount  DECIMAL(8,2)  NOT NULL DEFAULT 0.00,
    discount_reason  VARCHAR(40)       NULL,
    tax_rate         DECIMAL(6,5)  NOT NULL,
    CONSTRAINT pk_invoice            PRIMARY KEY (invoice_id),
    CONSTRAINT uq_invoice_work_order UNIQUE (work_order_id),
    CONSTRAINT fk_invoice_work_order FOREIGN KEY (work_order_id) REFERENCES work_order (work_order_id),
    CONSTRAINT ck_invoice_discount   CHECK (discount_amount >= 0
                                        AND (discount_amount = 0) = (discount_reason IS NULL)),
    CONSTRAINT ck_invoice_tax        CHECK (tax_rate BETWEEN 0 AND 0.15)
);

-- -----------------------------------------------------------------------------
-- 13. payment : an invoice can be settled by one or more payments
-- -----------------------------------------------------------------------------
CREATE TABLE payment (
    payment_id      INT UNSIGNED  NOT NULL AUTO_INCREMENT,
    invoice_id      INT UNSIGNED  NOT NULL,
    paid_at         DATETIME      NOT NULL,
    payment_method  VARCHAR(20)   NOT NULL,
    amount          DECIMAL(9,2)  NOT NULL,
    CONSTRAINT pk_payment         PRIMARY KEY (payment_id),
    CONSTRAINT fk_payment_invoice FOREIGN KEY (invoice_id) REFERENCES invoice (invoice_id),
    CONSTRAINT ck_payment_method  CHECK (payment_method IN
        ('Visa','Mastercard','American Express','Discover','Debit Card','Cash','Mobile Wallet','ACH / Check')),
    CONSTRAINT ck_payment_amount  CHECK (amount > 0),
    INDEX ix_payment_paid_at (paid_at)
);

-- -----------------------------------------------------------------------------
-- 14. customer_feedback : post-visit survey (1-5 stars), at most one per job
-- -----------------------------------------------------------------------------
CREATE TABLE customer_feedback (
    feedback_id    INT UNSIGNED     NOT NULL AUTO_INCREMENT,
    work_order_id  INT UNSIGNED     NOT NULL,
    submitted_at   DATETIME         NOT NULL,
    rating         TINYINT UNSIGNED NOT NULL,
    comment        VARCHAR(255)         NULL,
    CONSTRAINT pk_customer_feedback  PRIMARY KEY (feedback_id),
    CONSTRAINT uq_feedback_work_order UNIQUE (work_order_id),
    CONSTRAINT fk_feedback_work_order FOREIGN KEY (work_order_id) REFERENCES work_order (work_order_id),
    CONSTRAINT ck_feedback_rating    CHECK (rating BETWEEN 1 AND 5)
);
